CREATE TABLE GENDERS(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(255)
);

CREATE TABLE JOBS(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(255),
SALARY NUMBER NOT NULL
);

CREATE TABLE EMPLOYEES(
ID NUMBER PRIMARY KEY,
GENDER_ID NUMBER NOT NULL,
JOB_ID NUMBER NOT NULL,
NAME VARCHAR2(255) NOT NULL,
LAST_NAME VARCHAR2(255) NOT NULL,
BIRTHDATE DATE NOT NULL,
FOREIGN KEY (GENDER_ID) REFERENCES GENDERS(ID),
FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID)
);

CREATE TABLE EMPLOYEE_WORKED_HOURS(
ID NUMBER PRIMARY KEY,
EMPLOYEE_ID NUMBER NOT NULL,
WORKED_HOURS NUMBER NOT NULL,
WORKED_DATE DATE NOT NULL,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
);

-------GENEROS
INSERT INTO GENDERS VALUES(1,'MALE');
COMMIT;

------TRABAJOS
INSERT INTO JOBS VALUES(1, 'MANAGER', 25000);
COMMIT;

------EMPLEADOS
INSERT INTO EMPLOYEES VALUES(1, 1, 1, 'CARLOS', 'HERRERA', '20/07/1998');
COMMIT;

------HORAS TRABAJADAS
INSERT INTO EMPLOYEE_WORKED_HOURS VALUES(1,1, 10, '04/04/2025');
COMMIT;
